---
label: Site Configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: description
  label: Site Description
  description: The default site description used in meta data.
- type: select
  name: layout_style
  label: Layout Style
  description: The style of the theme layout
  default: grid
  config:
    source:
      type: custom
    options:
    - grid
    - list
- type: select
  name: palette
  label: Color Palette
  description: The color palette used for the site.
  default: green
  config:
    source:
      type: custom
    options:
    - black
    - blue
    - green
    - red
- type: field_group
  name: header
  label: Header Configuration
  fields:
  - type: text
    name: title
    label: Header Title
    description: The title displayed in the header if no logo image added.
  - type: file
    name: logo_img
    label: Logo
    description: The logo image displayed in the header.
  - type: boolean
    name: has_nav
    label: Enable Navigation Menu
    description: Display the navigation menu bar in the header.
    default: true
  - type: field_group_list
    name: nav_links
    label: Navigation Links
    description: List of navigation links.
    fields:
    - type: include
      name: include_action
      label: Action
      template: action
    config:
      labelField: label
- type: field_group
  name: footer
  label: Footer Configuration
  fields:
  - type: text
    name: content
    label: Footer Content
    description: The copyright text displayed in the footer.
  - type: field_group_list
    name: links
    label: Links
    description: List of links in the footer.
    fields:
    - type: include
      name: include_action
      label: Action
      template: action
    config:
      labelField: label
  - type: boolean
    name: has_social
    label: Enable Social Links
    description: Display social links in the footer.
    default: true
  - type: field_group_list
    name: social_links
    label: Social Links
    description: List of social links in the footer.
    fields:
    - type: include
      name: include_action
      label: Action
      template: action
    config:
      labelField: label
  - type: boolean
    name: has_subscribe
    label: Enable Subscribe Section
    description: Display the newsletter subscription section in the footer.
    default: true
  - type: text
    name: subscribe_title
    label: Title
    description: The title of the subscribe section.
  - type: text
    name: subscribe_content
    label: Content
    description: The text content of the subscribe section.
